export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          <div>MENU</div>
          <div>{children}</div>
        </div>
        <div></div>
      </body>
    </html>
  );
}
